### ISSUE TITLE
IO Exceptions when shutting down sensor and I2C bus. <bus> "has already been closed"

### ISSUE THREAD

**Issue by gjwo** [gjwo/RPISensors#1]
Example

> java.io.IOException: I2CBus '1' ('/dev/i2c-1') has already been closed! A new bus has to be aquired.
> 	at com.pi4j.io.i2c.impl.I2CBusImpl.testWhetherBusHasAlreadyBeenClosed(I2CBusImpl.java:298)
> 	at com.pi4j.io.i2c.impl.I2CBusImpl.testForProperOperationConditions(I2CBusImpl.java:289)
> 	at com.pi4j.io.i2c.impl.I2CBusImpl.readByte(I2CBusImpl.java:171)
> 	at com.pi4j.io.i2c.impl.I2CDeviceImpl.read(I2CDeviceImpl.java:225)
> 	at devices.I2C.Pi4jI2CDevice.read(Pi4jI2CDevice.java:22)
> 	at sensors.Implementations.MPU9250.MPU9250RegisterOperations.readByteRegister(MPU9250RegisterOperations.java:89)
> 	at sensors.Implementations.MPU9250.MPU9250Magnetometer.updateData(MPU9250Magnetometer.java:86)
> 	at sensors.models.NineDOF.updateData(NineDOF.java:133)
> 	at sensors.models.SensorPackage.run(SensorPackage.java:56)
> 	at java.lang.Thread.run(Thread.java:745)
> java.io.IOException: I2CBus '1' ('/dev/i2c-1') has already been closed! A new bus has to be aquired.
> 	at com.pi4j.io.i2c.impl.I2CBusImpl.testWhetherBusHasAlreadyBeenClosed(I2CBusImpl.java:298)
> 	at com.pi4j.io.i2c.impl.I2CBusImpl.testForProperOperationConditions(I2CBusImpl.java:289)
> 	at com.pi4j.io.i2c.impl.I2CBusImpl.readBytes(I2CBusImpl.java:182)
> 	at com.pi4j.io.i2c.impl.I2CDeviceImpl.read(I2CDeviceImpl.java:252)
> 	at devices.I2C.Pi4jI2CDevice.read(Pi4jI2CDevice.java:29)
> 	at sensors.Implementations.MPU9250.MPU9250RegisterOperations.readByteRegisters(MPU9250RegisterOperations.java:105)
> 	at sensors.Implementations.MPU9250.MPU9250Magnetometer.updateData(MPU9250Magnetometer.java:90)
> 	at sensors.models.NineDOF.updateData(NineDOF.java:133)
> 	at sensors.models.SensorPackage.run(SensorPackage.java:56)
> 	at java.lang.Thread.run(Thread.java:745)

I think this looks like some kind of  timing issue, but I can't spot it.

**Comment by gjwo** [comment]
Fixed
